### PR TITLE
Retrain models issue48

### PR DESCRIPTION
**Pull request by egrygorova**
added the new trained models for jsbd & jtbd

### CODE REVIEW

**Comment by fmatthies** [comment]
Did you also modify the descriptor to account for the new model file?

**Comment by egrygorova** [comment]
the name of the modelfile in the desc is now corresponding to the name of the model file

**Comment by fmatthies** [comment]
the tests aren't working... did they for you?

**Comment by egrygorova** [comment]
the test for the jsbd is working now, there was a small error in the desc
the test for jtbd already worked before

**Comment by fmatthies** [comment]
Could you also put the performance figures for the biomed models into the `README`s.
The overall performance for 10-fold-x-validation suffices (maybe have a new header `Performance` or some such with a short description -- see the documentations of the respective `base` projects).
Thanks.

**Comment by egrygorova** [comment]
ok i did it

**Comment by egrygorova** [comment]
please review the new README's, @fmatthies

**Pull request merged**
